"""Saved Photos

Revision ID: 017cd4d8435f
Revises: 4cb79852a4a0
Create Date: 2025-04-15 21:29:11.591179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017cd4d8435f'
down_revision: Union[str, None] = '4cb79852a4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_photos',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('num_images', sa.Integer(), nullable=False),
    sa.Column('author_uuid', sa.UUID(), nullable=False),
    sa.Column('file_uuid', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_uuid'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['file_uuid'], ['files.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_saved_photos_uuid'), 'saved_photos', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_photos_uuid'), table_name='saved_photos')
    op.drop_table('saved_photos')
    # ### end Alembic commands ###
