"""Create Files_processed

Revision ID: 0bfb9b6872a9
Revises: bc50e26f2254
Create Date: 2025-03-23 17:35:24.004423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bfb9b6872a9'
down_revision: Union[str, None] = 'bc50e26f2254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('s3_url_processed', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 's3_url_processed')
    # ### end Alembic commands ###
