"""Add contours url

Revision ID: 29f959a29b37
Revises: a288d4d1ccab
Create Date: 2025-05-13 16:13:14.200034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f959a29b37'
down_revision: Union[str, None] = 'a288d4d1ccab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contours', sa.Column('url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contours', 'url')
    # ### end Alembic commands ###
