"""Create Users

Revision ID: 582367ca0f45
Revises: 0bfb9b6872a9
Create Date: 2025-04-04 17:00:57.593179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582367ca0f45'
down_revision: Union[str, None] = '0bfb9b6872a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('files', sa.Column('author_id', sa.UUID(), nullable=True))
    op.add_column('files', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'files', 'users', ['author_id'], ['uuid'])
    op.drop_column('files', 's3_url')
    op.drop_column('files', 's3_url_processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('s3_url_processed', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('s3_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'is_public')
    op.drop_column('files', 'author_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
