"""Add constraints

Revision ID: 5d39c5f47fa9
Revises: 017cd4d8435f
Create Date: 2025-04-15 22:35:05.078480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d39c5f47fa9'
down_revision: Union[str, None] = '017cd4d8435f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_saved_photo', 'saved_photos', ['author_uuid', 'file_uuid', 'num_images'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_saved_photo', 'saved_photos', type_='unique')
    # ### end Alembic commands ###
