"""Create_Contours

Revision ID: 81b7cc8c4190
Revises: c60fd8c30709
Create Date: 2025-05-12 12:25:24.028052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81b7cc8c4190'
down_revision: Union[str, None] = 'c60fd8c30709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('num_images', sa.Integer(), nullable=False),
    sa.Column('file_uuid', sa.UUID(), nullable=False),
    sa.Column('contours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['file_uuid'], ['files.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contours_id'), 'contours', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contours_id'), table_name='contours')
    op.drop_table('contours')
    # ### end Alembic commands ###
