"""Add contours

Revision ID: a288d4d1ccab
Revises: 81b7cc8c4190
Create Date: 2025-05-13 15:28:46.156861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a288d4d1ccab'
down_revision: Union[str, None] = '81b7cc8c4190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contours', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contours', 'version')
    # ### end Alembic commands ###
