"""Create Files_num_slice

Revision ID: bc50e26f2254
Revises: e5d2771bdd35
Create Date: 2025-03-22 21:44:00.153491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc50e26f2254'
down_revision: Union[str, None] = 'e5d2771bdd35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('num_slices', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'num_slices')
    # ### end Alembic commands ###
